### ISSUE TITLE
Get `status` in contracts page to show up right

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#118]
First need to see what api is actually populating tables but either case, if it is `/addresses/contracts` (right) or `/contracts` (being phased out), `status` should be filled in. Right now, most contracts are missing it. 

Use `/addresses/contracts` where possible

**Comment by athoifss** [comment]
- Removed the extra api calls.
- Fixed the status empty bug

@robcxyz 
The status change handler is broken because the api with the three status query params all return the same result.
https://tracker.icon.community/api/v1/addresses/contracts?search=&skip=0&status=Active&limit=25
https://tracker.icon.community/api/v1/addresses/contracts?search=&skip=0&status=Pending&limit=25
https://tracker.icon.community/api/v1/addresses/contracts?search=&skip=0&status=Rejected&limit=25

All three return the same data.
