### ISSUE TITLE
Wrong decimals for IUSDC on tracker

### ISSUE THREAD

**Issue by oDK1** [sudoblockio/icon-tracker-frontend#137]
### Issue type 

- [v ] Bug 
- [ ] Feature request

### Issue Description

Wrong decimals for IUSDC (shows IUSDC with more decimals than necessary)

Description

### Link / Screenshot
<img width="1187" alt="Screen Shot 2023-01-19 at 3 54 11 PM" src="https://user-images.githubusercontent.com/51342586/213587900-674e83fb-3f56-4b63-b505-3467c3c417c4.png">

[//]: # (If the issue can be found through a link it **MUST** be included. Screenshot optional but helpful)

https://tracker.icon.community/address/cx4f3c2edf730f203b1ef1257d645415652ae8b4fb

### Steps to Reproduce the Problem / Desired Outcome 

[//]: # (Not always relevant if link is included)

1. 
2.

**Comment by robcxyz** [comment]
@athoifss - Here we are not dividing by the right decimals which is returned from the https://tracker.icon.community/api/v1/contracts/cxae3034235540b924dfcc1b45836c293dcc82bfb7 call 

This call is made on each of the tokens returned in https://tracker.icon.community/api/v1/addresses/token-addresses/cx4f3c2edf730f203b1ef1257d645415652ae8b4fb

It also seems to be made twice. 

So in this case, you need to use the decimals from the `/contracts/addr` call instead of the standard `18` (0x12)

**Comment by athoifss** [comment]
@robcxyz , the api response has a **value_decimal** field. I replaced the old display value (involved some calculation logic) with this value.
