### ISSUE TITLE
Estimated blockheight not shown in tracker while unstaking

### ISSUE THREAD

**Issue by iconistjohn** [sudoblockio/icon-tracker-frontend#443]
Community reports that wallets are not showing the target blockheight in the tracker for wallets that are unstaking an ICX balance.

See Discord discussion below for reference.
https://discord.com/channels/880651922682560582/888150941910585374/1228688168774271070

Or contact iconjohn via Discord for an example wallet address.

**Comment by robcxyz** [comment]
This is an issue. 

@athoifss - I think this was caused here. https://github.com/sudoblockio/icon-tracker-frontend/commit/1711c690af73068c681b5bdacf3a86f4c42007be

Check this comment https://github.com/sudoblockio/icon-tracker-frontend/issues/411#issuecomment-1987110624

What I think happened is you just commented the data out because you didn't see any changes. 

Commented about that here -> https://github.com/sudoblockio/icon-tracker-frontend/issues/411#issuecomment-2016529820

Issue was closed so I'll reopen it.

**Comment by robcxyz** [comment]
This was fixed a month back and forgot to close
